In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_excel("DWM.xlsx")


In [ ]:
x= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
print(x)
print(y)

[[0 'BUNK Hotel Amsterdam' 'Bunk Pod for 2' ... 8.4 7887 65]
 [1 'YOTEL Amsterdam' 'Premium Double Room' ... 8.1 15267 65]
 [2 'Multatuli Hotel' 'Double Room' ... 7.4 13063 64]
 ...
 [522 'The Cabin at Zwolle Centraal' 'Double Room with Private Bathroom'
  ... 7.2 6123 64]
 [523 'Hanze Hotel Zwolle' 'Standard Twin Room' ... 7.2 7789 65]
 [524 'Campanile Hotel & Restaurant Zwolle' 'Double Room' ... 6.4 6870 67]]
[7.780e+02 5.000e+02 1.605e+03 5.000e+02 5.000e+02 1.264e+03 5.000e+02
 5.000e+02 2.069e+03       nan 5.000e+02 5.000e+02 5.000e+02 5.000e+02
 2.974e+03 5.000e+02 1.278e+03 5.000e+02 5.000e+02 1.935e+03 5.180e+02
 2.064e+03 1.629e+03 5.000e+02 1.783e+03 1.000e+00 1.000e+00 2.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 4.000e+00 1.155e+03 1.800e+01
 5.000e+00 1.800e+01 4.000e+01 1.800e+01 1.000e+00 1.800e+01 1.000e+00
 1.000e+00 1.800e+01 1.800e+01 1.800e+01 1.900e+01 1.800e+01 3.000e+00
 1.000e+00 8.800e+01 3.600e+01 5.000e+02 1.250e+02 3.530e+02 1.310e+02
 8.410e+02 5.000e

In [ ]:
print(dataset)

     Hotel_id                                 Name  \
0           0                 BUNK Hotel Amsterdam   
1           1                      YOTEL Amsterdam   
2           2                      Multatuli Hotel   
3           3                   nhow Amsterdam Rai   
4           4                  Motel One Amsterdam   
..        ...                                  ...   
520       520     Stadslogement Bij de Sassenpoort   
521       521                 Mercure Hotel Zwolle   
522       522         The Cabin at Zwolle Centraal   
523       523                   Hanze Hotel Zwolle   
524       524  Campanile Hotel & Restaurant Zwolle   

                                   Type                   City  Rating(10)  \
0                        Bunk Pod for 2        Amsterdam Noord         8.4   
1                   Premium Double Room        Amsterdam Noord         8.1   
2                           Double Room  Amsterdam City Center         7.4   
3    nhow Double or Twin Room with View

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,4:7])
x=imputer.transform(x[:,4:7])

# New Section

In [ ]:
print(x)

[[8.4000e+00 7.8870e+03 6.5000e+01]
 [8.1000e+00 1.5267e+04 6.5000e+01]
 [7.4000e+00 1.3063e+04 6.4000e+01]
 ...
 [7.2000e+00 6.1230e+03 6.4000e+01]
 [7.2000e+00 7.7890e+03 6.5000e+01]
 [6.4000e+00 6.8700e+03 6.7000e+01]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

  (0, 25)	1.0
  (0, 41)	7887.0
  (0, 42)	65.0
  (1, 21)	1.0
  (1, 41)	15267.0
  (1, 42)	65.0
  (2, 14)	1.0
  (2, 41)	13063.0
  (2, 42)	64.0
  (3, 31)	1.0
  (3, 41)	12854.0
  (3, 42)	66.0
  (4, 29)	1.0
  (4, 41)	9471.0
  (4, 42)	65.0
  (5, 25)	1.0
  (5, 41)	14123.0
  (5, 42)	65.0
  (6, 23)	1.0
  (6, 41)	20060.0
  (6, 42)	65.0
  (7, 29)	1.0
  (7, 41)	14206.0
  (7, 42)	65.0
  (8, 13)	1.0
  :	:
  (516, 42)	75.0
  (517, 21)	1.0
  (517, 41)	7348.0
  (517, 42)	67.0
  (518, 22)	1.0
  (518, 41)	7838.0
  (518, 42)	65.0
  (519, 22)	1.0
  (519, 41)	8532.0
  (519, 42)	64.0
  (520, 25)	1.0
  (520, 41)	8899.0
  (520, 42)	65.0
  (521, 17)	1.0
  (521, 41)	10205.0
  (521, 42)	67.0
  (522, 12)	1.0
  (522, 41)	6123.0
  (522, 42)	64.0
  (523, 12)	1.0
  (523, 41)	7789.0
  (523, 42)	65.0
  (524, 4)	1.0
  (524, 41)	6870.0
  (524, 42)	67.0


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = np.array(le.fit_transform(y))

In [ ]:
print(y)

[168 120 250 120 120 230 120 120 267 305 120 120 120 120 286 120 231 120
 120 263 124 266 251 120 258   0   0   1   0   0   0   0   3 223  13   4
  13  23  13   0  13   0   0  13  13  13  14  13   2   0  42  21 120  52
 100  53 179 120 112 120 120 205 108 120 220 173 218 120 228 154  48 120
 120 210 220  32  97  35 213 120 120 120 119 128 246  10 248 151 271 264
 152 132 139  80  81 183  82 120  45 120 221  34 196  63 120 120  61 120
 120   3 120 203 198 120  74  33  89 287 120 120 302 241 276  20 120 120
 253 171 174 120 254 120 120 120 283 187 120 120 120  31   3   8 120 232
 120 177 233   1 147 120  39 158  66 120  50 120 120 278 120   1   3 261
  49  57 141  19   5 114 120 120 181  57 272  65 156 189 126 120  72 212
  86 257  60 120 232 175 162 131  91 115 120 102   6 288 105 234 182 120
 206 120 120  27 293 120  90 120 204  12 120 116 118 270 120 163 202 120
 120 120  23  98 120 120 281 165 297 120  55 120 260 136 120 120  56 120
 275 209 105 120  23 120 256 120 117  84 120 120 12

In [ ]:
dataset['ReviewsCount'].describe()

count     512.000000
mean      736.556641
std       879.553639
min         1.000000
25%       239.000000
50%       500.000000
75%       888.000000
max      7748.000000
Name: ReviewsCount, dtype: float64

In [ ]:
x= dataset.iloc[:,:4:6].values
y= dataset.iloc[:,6].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 0:] = sc.fit_transform(x_train[:, 0:])
x_test[:, 0:] = sc.transform(x_test[:, 0:])

In [ ]:
print(x_test)

[[ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 1]
 [-1]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 1]
 [ 1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 0]
 [ 1]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 1]
 [-1]
 [-1]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 1]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 1]
 [ 1]
 [ 1]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 1]
 [ 0]]


In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
x_predict = np.array(x_test[:,:])
print(classifier.predict((x_predict)))

accuracy = classifier.score(x_test,y_test)
print(accuracy)

[65 67 67 67 67 67 65 67 67 67 67 65 65 67 67 67 67 65 67 65 67 67 67 65
 67 67 67 67 65 67 67 65 65 67 65 67 67 67 67 67 67 65 65 67 67 65 67 67
 67 67 67 65 67 65 65 65 65 67 65 67 65 67 67 65 65 65 67 67 67 65 67 67
 65 67 67 67 65 67 67 67 67 67 65 65 65 67 67 67 67 67 67 67 67 67 65 65
 65 67 65 67 67 65 67 65 67]
0.38095238095238093


In [ ]:
print(y_test)

[67 67 67 71 65 75 67 69 82 65 67 65 67 65 65 65 67 65 64 65 67 67 65 67
 86 69 67 67 67 65 66 65 64 67 57 64 65 65 67 73 65 65 65 67 66 65 75 68
 67 73 67 65 67 65 65 70 65 65 65 69 67 65 65 65 67 65 67 72 65 67 72 76
 70 64 67 68 67 67 65 65 72 67 65 65 67 65 67 65 65 67 67 65 67 65 68 65
 67 68 65 65 80 67 65 67 80]


Naive Bayes Classification

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()