# Decision Tree Classification

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_excel('dwm2.xlsx')
dataset=dataset.dropna(how='any')
X = dataset.iloc[:, 2:6].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

    Hotel_id                                               Name  Rating(10)  \
0          0                               BUNK Hotel Amsterdam         8.4   
1          1                                    YOTEL Amsterdam         8.1   
2          2                                    Multatuli Hotel         7.4   
3          3                                 nhow Amsterdam Rai         9.0   
5          5                         INNSiDE by Meliá Amsterdam         8.4   
6          6                               Eden Hotel Amsterdam         8.3   
7          7                           citizenM Amsterdam South         8.8   
8          8                                   The Alfred Hotel         7.3   
10        10                            Hyatt Regency Amsterdam         8.5   
11        11              NH Collection Amsterdam Flower Market         8.6   
12        12              ibis Styles Amsterdam Central Station         7.9   
13        13                     Leonardo Royal Hote

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y = np.array(le.fit_transform(y))

In [ ]:
y=y.reshape([-1,1])
print(y)

[[1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[ 8.99134918e-01 -5.79997247e-02]
 [-7.25782912e-01 -5.71904262e-01]
 [-4.60512642e-01 -5.71904262e-01]
 [-7.42116901e-01 -5.71904262e-01]
 [-3.31882475e-01 -5.71904262e-01]
 [-4.72920191e-01 -5.79997247e-02]
 [ 4.76492942e-01  1.22676162e+00]
 [ 4.88743434e-01 -5.71904262e-01]
 [-5.35900285e-01 -5.71904262e-01]
 [ 2.83626221e-01 -5.71904262e-01]
 [-4.08840694e-01 -5.71904262e-01]
 [ 2.96504944e-01 -5.71904262e-01]
 [-1.26608205e-01  9.69809350e-01]
 [ 1.82231943e+00 -5.71904262e-01]
 [-1.33579459e+00 -5.71904262e-01]
 [-9.44564135e-01 -5.71904262e-01]
 [-3.87637920e-01 -5.79997247e-02]
 [-6.95941970e-01 -5.71904262e-01]
 [ 2.43782813e+00  2.51152296e+00]
 [ 7.85090084e-02  1.98952544e-01]
 [ 2.06510944e-01 -5.71904262e-01]
 [-2.40495981e-02 -5.79997247e-02]
 [-9.88383203e-01 -5.71904262e-01]
 [ 8.87512656e-01  1.98952544e-01]
 [ 1.13896186e+00 -5.71904262e-01]
 [-4.85641856e-01  4.55904813e-01]
 [-3.95961972e-01 -2.62752241e+00]
 [-4.08840694e-01 -5.71904262e-01]
 [-6.95941970e-01 -5

In [ ]:
print(y_train)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [ ]:
print(X_test)

[[8.1000e+00 1.1838e+04 6.5000e+01 1.1550e+03]
 [8.1000e+00 2.0982e+04 6.7000e+01 1.8000e+01]
 [8.5000e+00 1.1336e+04 6.5000e+01 5.0000e+02]
 [8.1000e+00 2.0982e+04 6.7000e+01 1.8000e+01]
 [7.4000e+00 1.3063e+04 6.4000e+01 1.6050e+03]
 [8.1000e+00 2.0982e+04 6.7000e+01 5.0000e+00]
 [8.1000e+00 2.6534e+04 6.5000e+01 1.9000e+01]
 [8.1000e+00 2.0982e+04 6.5000e+01 1.8000e+01]
 [9.0000e+00 2.8330e+04 6.7000e+01 1.0000e+00]
 [8.4000e+00 1.4123e+04 6.5000e+01 1.2640e+03]
 [7.9000e+00 1.7798e+04 6.7000e+01 5.0000e+02]
 [9.0000e+00 2.0982e+04 6.6000e+01 2.0000e+00]
 [8.1000e+00 2.0982e+04 6.5000e+01 4.0000e+01]]


In [ ]:
print(y_test)

[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-6.39361474e-01  3.19608322e-01 -4.79520719e-01 -7.32007640e-01]
 [-8.00233070e-01  1.28571519e+00  2.99700449e-01 -7.61039807e-01]
 [-8.00233070e-01  1.28571519e+00 -4.79520719e-01 -7.64910763e-01]
 [-1.92633425e+00 -7.75216383e-01 -4.79520719e-01  3.23765738e+00]
 [ 4.86739703e-01  2.11232297e+00  2.99700449e-01  2.00892673e-01]
 [-8.00233070e-01  3.19608322e-01 -4.79520719e-01 -7.64910763e-01]
 [ 6.47611299e-01 -1.07959001e+00  2.99700449e-01  2.00892673e-01]
 [ 1.64996509e-01  3.47613325e-01  3.41658512e+00  2.38604714e+00]
 [ 4.12491273e-03 -1.52556640e+00  2.99700449e-01 -5.13298645e-01]
 [-8.00233070e-01  3.19608322e-01  2.99700449e-01 -7.64910763e-01]
 [-9.61104667e-01 -1.37633786e+00 -4.79520719e-01  2.00892673e-01]
 [-3.17618280e-01  1.98384786e-01 -4.79520719e-01  2.00892673e-01]
 [ 4.12491273e-03  1.28571519e+00  2.99700449e-01 -7.59104329e-01]
 [-1.12197626e+00 -7.30907997e-01  2.99700449e-01  2.97830335e+00]
 [ 6.47611299e-01 -3.45937812e-01 -4.79520719e-01  5.37963580e

In [ ]:
print(X_test)

[[-0.63936147 -0.88263463 -0.47952072  1.46863065]
 [-0.63936147  0.31960832  0.29970045 -0.73200764]
 [ 0.00412491 -0.94863704 -0.47952072  0.20089267]
 [-0.63936147  0.31960832  0.29970045 -0.73200764]
 [-1.76546265 -0.721573   -0.8691313   2.33959567]
 [-0.63936147  0.31960832  0.29970045 -0.75716885]
 [-0.63936147  1.04957911 -0.47952072 -0.73007216]
 [-0.63936147  0.31960832 -0.47952072 -0.73200764]
 [ 0.8084829   1.28571519  0.29970045 -0.76491076]
 [-0.15674668 -0.58220537 -0.47952072  1.67959773]
 [-0.96110467 -0.09902046  0.29970045  0.20089267]
 [ 0.8084829   0.31960832 -0.08991013 -0.76297528]
 [-0.63936147  0.31960832 -0.47952072 -0.68942713]]


In [1]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

NameError: ignored

In [ ]:
print(classifier.predict(sc.transform([[9.4,17000,67,700]])))

[1]


In [ ]:
y_pred = classifier.predict(X_test)
print(y_pred)
print(y_test)

[1 0 1 0 0 0 0 0 0 1 1 0 0]
[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[7 1]
 [2 3]]


0.7692307692307693